version: "3.9"
services:
  hs-db:
    container_name: hs-db
    image: aidbox/db:yangand
    ports:
      - 127.0.0.1:5400:5432
    environment:
      POSTGRES_PASSWORD: postgres
    deploy:
      resources:
        limits:
          cpus: '0.1'
    volumes:
      - "./pgdata:/data/"
      - "./:/opt/host/"
